import { Product } from "@/types";

export const ADULT_SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
export const KIDS_SIZES = ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"];

export const products: Product[] = [
  {
    id: "men-1",
    category: "men",
    brand: "AtyaKart Originals",
    name: "Classic Oxford Shirt",
    price: 1299,
    originalPrice: 2199,
    discountPercent: 41,
    rating: 4.4,
    reviewCount: 812,
    badge: "BESTSELLER",
    emoji: "👔",
    isNew: false,
    tags: ["shirt", "formal", "office"],
    sizes: ADULT_SIZES,
    description: "A tailored oxford shirt in breathable cotton — sharp enough for the boardroom, easy enough for everyday.",
  },
  {
    id: "men-2",
    category: "men",
    brand: "Urban Thread",
    name: "Slim Fit Stretch Jeans",
    price: 1599,
    originalPrice: 2999,
    discountPercent: 47,
    rating: 4.2,
    reviewCount: 1340,
    badge: "50% OFF",
    emoji: "👖",
    isNew: false,
    tags: ["jeans", "denim", "casual"],
    sizes: ADULT_SIZES,
    description: "Stretch-cotton denim with a modern slim fit that moves with you all day long.",
  },
  {
    id: "men-3",
    category: "men",
    brand: "AtyaKart Formals",
    name: "Tailored Blazer",
    price: 3499,
    originalPrice: 5999,
    discountPercent: 42,
    rating: 4.6,
    reviewCount: 456,
    badge: "PREMIUM",
    emoji: "🧥",
    isNew: false,
    tags: ["blazer", "formal", "office"],
    sizes: ADULT_SIZES,
    description: "A structured two-button blazer with soft shoulders — instantly elevates any outfit.",
  },
  {
    id: "men-4",
    category: "men",
    brand: "Desi Roots",
    name: "Embroidered Kurta Set",
    price: 1899,
    originalPrice: 2999,
    discountPercent: 37,
    rating: 4.5,
    reviewCount: 623,
    badge: "NEW",
    emoji: "🥻",
    isNew: true,
    tags: ["ethnic", "kurta", "festive"],
    sizes: ADULT_SIZES,
    description: "Hand-embroidered kurta and pyjama set in pure cotton — festive-ready, all-day comfortable.",
  },
  {
    id: "women-1",
    category: "women",
    brand: "Saree Studio",
    name: "Banarasi Silk Saree",
    price: 4299,
    originalPrice: 7999,
    discountPercent: 46,
    rating: 4.7,
    reviewCount: 998,
    badge: "BESTSELLER",
    emoji: "🥻",
    isNew: false,
    tags: ["saree", "ethnic", "wedding"],
    sizes: ["Free Size"],
    description: "A handwoven Banarasi silk saree with intricate zari borders — timeless elegance for every celebration.",
  },
  {
    id: "women-2",
    category: "women",
    brand: "Indie Threads",
    name: "Printed Anarkali Kurta",
    price: 1199,
    originalPrice: 2199,
    discountPercent: 45,
    rating: 4.3,
    reviewCount: 1102,
    badge: "50% OFF",
    emoji: "👗",
    isNew: false,
    tags: ["kurta", "ethnic", "casual"],
    sizes: ADULT_SIZES,
    description: "A flowing Anarkali kurta in soft rayon with a vibrant block print — effortlessly graceful.",
  },
  {
    id: "women-3",
    category: "women",
    brand: "Aura Studio",
    name: "Floral Wrap Dress",
    price: 1799,
    originalPrice: 2999,
    discountPercent: 40,
    rating: 4.4,
    reviewCount: 567,
    badge: "TRENDING",
    emoji: "👗",
    isNew: false,
    tags: ["dress", "western", "casual"],
    sizes: ADULT_SIZES,
    description: "A flattering wrap silhouette in flowy crepe — your go-to for brunch dates and beyond.",
  },
  {
    id: "women-4",
    category: "women",
    brand: "FusionFit",
    name: "Indo-Western Co-ord Set",
    price: 2199,
    originalPrice: 3799,
    discountPercent: 42,
    rating: 4.5,
    reviewCount: 389,
    badge: "NEW",
    emoji: "👚",
    isNew: true,
    tags: ["fusion", "coord", "party"],
    sizes: ADULT_SIZES,
    description: "A breezy fusion co-ord set blending traditional prints with a contemporary silhouette.",
  },
  {
    id: "kids-1",
    category: "kids",
    brand: "Tiny Trends",
    name: "Dino Print Tee & Shorts Set",
    price: 699,
    originalPrice: 1199,
    discountPercent: 42,
    rating: 4.3,
    reviewCount: 712,
    badge: "BESTSELLER",
    emoji: "🦖",
    isNew: false,
    tags: ["boys", "casual", "set"],
    sizes: KIDS_SIZES,
    description: "Soft cotton tee and shorts set with a fun dino print — built tough for endless play.",
  },
  {
    id: "kids-2",
    category: "kids",
    brand: "Little Belle",
    name: "Party Frock with Bow",
    price: 1099,
    originalPrice: 1899,
    discountPercent: 42,
    rating: 4.6,
    reviewCount: 304,
    badge: "PARTY WEAR",
    emoji: "👧",
    isNew: false,
    tags: ["girls", "party", "dress"],
    sizes: KIDS_SIZES,
    description: "A twirl-ready party frock with a satin bow and soft tulle lining — pure party magic.",
  },
  {
    id: "kids-3",
    category: "kids",
    brand: "Snuggle Buds",
    name: "Infant Romper Combo (Pack of 3)",
    price: 899,
    originalPrice: 1499,
    discountPercent: 40,
    rating: 4.5,
    reviewCount: 521,
    badge: "NEW",
    emoji: "🍼",
    isNew: true,
    tags: ["infants", "casual", "combo"],
    sizes: ["0-3M", "3-6M", "6-12M"],
    description: "A pack of 3 super-soft cotton rompers with snap buttons — gentle on delicate skin.",
  },
  {
    id: "kids-4",
    category: "kids",
    brand: "Campus Kids",
    name: "School Uniform Shirt & Trouser Set",
    price: 799,
    originalPrice: 1299,
    discountPercent: 38,
    rating: 4.2,
    reviewCount: 233,
    badge: "SCHOOL ESSENTIAL",
    emoji: "🎒",
    isNew: false,
    tags: ["school", "uniform", "set"],
    sizes: KIDS_SIZES,
    description: "Durable, easy-iron uniform set designed to survive playground adventures and homework alike.",
  },
  {
    id: "zeng-1",
    category: "zeng",
    brand: "ZenG Wellness",
    name: "Organic Cotton Lounge Set",
    price: 1599,
    originalPrice: 2599,
    discountPercent: 38,
    rating: 4.6,
    reviewCount: 287,
    badge: "NEW",
    emoji: "🧘",
    isNew: true,
    tags: ["loungewear", "organic", "wellness"],
    sizes: ADULT_SIZES,
    description: "GOTS-certified organic cotton lounge set — breathable, chemical-free, and made for stillness.",
  },
  {
    id: "zeng-2",
    category: "zeng",
    brand: "ZenG Linen Co.",
    name: "Pure Linen Co-ord Set",
    price: 2299,
    originalPrice: 3599,
    discountPercent: 36,
    rating: 4.5,
    reviewCount: 198,
    badge: "TRENDING",
    emoji: "🌿",
    isNew: false,
    tags: ["linen", "coord", "minimal"],
    sizes: ADULT_SIZES,
    description: "Breathable European linen co-ord set in earthy tones — slow fashion that feels as good as it looks.",
  },
  {
    id: "zeng-3",
    category: "zeng",
    brand: "ZenG Wellness",
    name: "Bamboo Fibre Yoga Wrap Top",
    price: 999,
    originalPrice: 1699,
    discountPercent: 41,
    rating: 4.4,
    reviewCount: 156,
    badge: "BESTSELLER",
    emoji: "🧘‍♀️",
    isNew: false,
    tags: ["activewear", "yoga", "sustainable"],
    sizes: ADULT_SIZES,
    description: "Ultra-soft bamboo fibre wrap top with four-way stretch — moves with you through every asana.",
  },
  {
    id: "zeng-4",
    category: "zeng",
    brand: "ZenG Naturals",
    name: "Hemp Blend Relaxed Joggers",
    price: 1399,
    originalPrice: 2199,
    discountPercent: 36,
    rating: 4.3,
    reviewCount: 142,
    badge: "ECO-FRIENDLY",
    emoji: "🍃",
    isNew: false,
    tags: ["joggers", "sustainable", "loungewear"],
    sizes: ADULT_SIZES,
    description: "Relaxed-fit joggers in a hemp-cotton blend — naturally breathable, gentle on the planet.",
  },
];

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}
