import { Product } from "@/types";

export const ADULT_SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
export const KIDS_SIZES = ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-12Y"];
export const BEAUTY_SIZES = ["Standard"];

export const products: Product[] = [
  {
    id: "men-1",
    category: "men",
    brand: "AtyaKart Originals",
    name: "Classic Oxford Shirt",
    price: 1299,
    originalPrice: 2199,
    discountPercent: 41,
    rating: 4.4,
    reviewCount: 812,
    badge: "BESTSELLER",
    emoji: "👔",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["shirt", "formal", "office"],
    sizes: ADULT_SIZES,
    description: "A tailored oxford shirt in breathable cotton — sharp enough for the boardroom, easy enough for everyday.",
  },
  {
    id: "men-2",
    category: "men",
    brand: "Urban Thread",
    name: "Slim Fit Stretch Jeans",
    price: 1599,
    originalPrice: 2999,
    discountPercent: 47,
    rating: 4.2,
    reviewCount: 1340,
    badge: "50% OFF",
    emoji: "👖",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["jeans", "denim", "casual"],
    sizes: ADULT_SIZES,
    description: "Stretch-cotton denim with a modern slim fit that moves with you all day long.",
  },
  {
    id: "men-3",
    category: "men",
    brand: "AtyaKart Formals",
    name: "Tailored Blazer",
    price: 3499,
    originalPrice: 5999,
    discountPercent: 42,
    rating: 4.6,
    reviewCount: 456,
    badge: "PREMIUM",
    emoji: "🧥",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["blazer", "formal", "office"],
    sizes: ADULT_SIZES,
    description: "A structured two-button blazer with soft shoulders — instantly elevates any outfit.",
  },
  {
    id: "men-4",
    category: "men",
    brand: "Desi Roots",
    name: "Embroidered Kurta Set",
    price: 1899,
    originalPrice: 2999,
    discountPercent: 37,
    rating: 4.5,
    reviewCount: 623,
    badge: "NEW",
    emoji: "🥻",
    image: "https://images.unsplash.com/photo-1505022610485-0249ba5b3675?w=600&h=750&fit=crop&q=70",
    isNew: true,
    tags: ["ethnic", "kurta", "festive"],
    sizes: ADULT_SIZES,
    description: "Hand-embroidered kurta and pyjama set in pure cotton — festive-ready, all-day comfortable.",
  },
  {
    id: "women-1",
    category: "women",
    brand: "Saree Studio",
    name: "Banarasi Silk Saree",
    price: 4299,
    originalPrice: 7999,
    discountPercent: 46,
    rating: 4.7,
    reviewCount: 998,
    badge: "BESTSELLER",
    emoji: "🥻",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["saree", "ethnic", "wedding"],
    sizes: ["Free Size"],
    description: "A handwoven Banarasi silk saree with intricate zari borders — timeless elegance for every celebration.",
  },
  {
    id: "women-2",
    category: "women",
    brand: "Indie Threads",
    name: "Printed Anarkali Kurta",
    price: 1199,
    originalPrice: 2199,
    discountPercent: 45,
    rating: 4.3,
    reviewCount: 1102,
    badge: "50% OFF",
    emoji: "👗",
    image: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["kurta", "ethnic", "casual"],
    sizes: ADULT_SIZES,
    description: "A flowing Anarkali kurta in soft rayon with a vibrant block print — effortlessly graceful.",
  },
  {
    id: "women-3",
    category: "women",
    brand: "Aura Studio",
    name: "Floral Wrap Dress",
    price: 1799,
    originalPrice: 2999,
    discountPercent: 40,
    rating: 4.4,
    reviewCount: 567,
    badge: "TRENDING",
    emoji: "👗",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["dress", "western", "casual"],
    sizes: ADULT_SIZES,
    description: "A flattering wrap silhouette in flowy crepe — your go-to for brunch dates and beyond.",
  },
  {
    id: "women-4",
    category: "women",
    brand: "FusionFit",
    name: "Indo-Western Co-ord Set",
    price: 2199,
    originalPrice: 3799,
    discountPercent: 42,
    rating: 4.5,
    reviewCount: 389,
    badge: "NEW",
    emoji: "👚",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&h=750&fit=crop&q=70",
    isNew: true,
    tags: ["fusion", "coord", "party"],
    sizes: ADULT_SIZES,
    description: "A breezy fusion co-ord set blending traditional prints with a contemporary silhouette.",
  },
  {
    id: "kids-1",
    category: "kids",
    brand: "Tiny Trends",
    name: "Dino Print Tee & Shorts Set",
    price: 699,
    originalPrice: 1199,
    discountPercent: 42,
    rating: 4.3,
    reviewCount: 712,
    badge: "BESTSELLER",
    emoji: "🦖",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["boys", "casual", "set"],
    sizes: KIDS_SIZES,
    description: "Soft cotton tee and shorts set with a fun dino print — built tough for endless play.",
  },
  {
    id: "kids-2",
    category: "kids",
    brand: "Little Belle",
    name: "Party Frock with Bow",
    price: 1099,
    originalPrice: 1899,
    discountPercent: 42,
    rating: 4.6,
    reviewCount: 304,
    badge: "PARTY WEAR",
    emoji: "👧",
    image: "https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["girls", "party", "dress"],
    sizes: KIDS_SIZES,
    description: "A twirl-ready party frock with a satin bow and soft tulle lining — pure party magic.",
  },
  {
    id: "kids-3",
    category: "kids",
    brand: "Snuggle Buds",
    name: "Infant Romper Combo (Pack of 3)",
    price: 899,
    originalPrice: 1499,
    discountPercent: 40,
    rating: 4.5,
    reviewCount: 521,
    badge: "NEW",
    emoji: "🍼",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&h=750&fit=crop&q=70",
    isNew: true,
    tags: ["infants", "casual", "combo"],
    sizes: ["0-3M", "3-6M", "6-12M"],
    description: "A pack of 3 super-soft cotton rompers with snap buttons — gentle on delicate skin.",
  },
  {
    id: "kids-4",
    category: "kids",
    brand: "Campus Kids",
    name: "School Uniform Shirt & Trouser Set",
    price: 799,
    originalPrice: 1299,
    discountPercent: 38,
    rating: 4.2,
    reviewCount: 233,
    badge: "SCHOOL ESSENTIAL",
    emoji: "🎒",
    image: "https://images.unsplash.com/photo-1503185912284-5271ff81b9a8?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["school", "uniform", "set"],
    sizes: KIDS_SIZES,
    description: "Durable, easy-iron uniform set designed to survive playground adventures and homework alike.",
  },
  {
    id: "zeng-1",
    category: "zeng",
    brand: "ZenG Wellness",
    name: "Organic Cotton Lounge Set",
    price: 1599,
    originalPrice: 2599,
    discountPercent: 38,
    rating: 4.6,
    reviewCount: 287,
    badge: "NEW",
    emoji: "🧘",
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&h=750&fit=crop&q=70",
    isNew: true,
    tags: ["loungewear", "organic", "wellness"],
    sizes: ADULT_SIZES,
    description: "GOTS-certified organic cotton lounge set — breathable, chemical-free, and made for stillness.",
  },
  {
    id: "zeng-2",
    category: "zeng",
    brand: "ZenG Linen Co.",
    name: "Pure Linen Co-ord Set",
    price: 2299,
    originalPrice: 3599,
    discountPercent: 36,
    rating: 4.5,
    reviewCount: 198,
    badge: "TRENDING",
    emoji: "🌿",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["linen", "coord", "minimal"],
    sizes: ADULT_SIZES,
    description: "Breathable European linen co-ord set in earthy tones — slow fashion that feels as good as it looks.",
  },
  {
    id: "zeng-3",
    category: "zeng",
    brand: "ZenG Wellness",
    name: "Bamboo Fibre Yoga Wrap Top",
    price: 999,
    originalPrice: 1699,
    discountPercent: 41,
    rating: 4.4,
    reviewCount: 156,
    badge: "BESTSELLER",
    emoji: "🧘‍♀️",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["activewear", "yoga", "sustainable"],
    sizes: ADULT_SIZES,
    description: "Ultra-soft bamboo fibre wrap top with four-way stretch — moves with you through every asana.",
  },
  {
    id: "zeng-4",
    category: "zeng",
    brand: "ZenG Naturals",
    name: "Hemp Blend Relaxed Joggers",
    price: 1399,
    originalPrice: 2199,
    discountPercent: 36,
    rating: 4.3,
    reviewCount: 142,
    badge: "ECO-FRIENDLY",
    emoji: "🍃",
    image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["joggers", "sustainable", "loungewear"],
    sizes: ADULT_SIZES,
    description: "Relaxed-fit joggers in a hemp-cotton blend — naturally breathable, gentle on the planet.",
  },
  {
    id: "beauty-1",
    category: "beauty",
    brand: "GlowLab",
    name: "Vitamin C Brightening Serum",
    price: 599,
    originalPrice: 999,
    discountPercent: 40,
    rating: 4.5,
    reviewCount: 2104,
    badge: "BESTSELLER",
    emoji: "🧴",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["skincare", "serum", "face"],
    sizes: BEAUTY_SIZES,
    description: "A lightweight vitamin C serum that brightens, evens skin tone, and fades dark spots with daily use.",
  },
  {
    id: "beauty-2",
    category: "beauty",
    brand: "Velvet Hue",
    name: "Matte Liquid Lipstick",
    price: 449,
    originalPrice: 799,
    discountPercent: 44,
    rating: 4.3,
    reviewCount: 1567,
    badge: "TRENDING",
    emoji: "💄",
    image: "https://images.unsplash.com/photo-1631214540242-3cd8c4b0b3b3?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["makeup", "lipstick", "color"],
    sizes: BEAUTY_SIZES,
    description: "A featherlight matte lipstick with full-pigment colour payoff and up to 8 hours of wear.",
  },
  {
    id: "beauty-3",
    category: "beauty",
    brand: "Root & Bloom",
    name: "Argan Hair Repair Oil",
    price: 399,
    originalPrice: 699,
    discountPercent: 43,
    rating: 4.4,
    reviewCount: 980,
    badge: "NEW",
    emoji: "🧖",
    image: "https://images.unsplash.com/photo-1556228852-80b6e21e1257?w=600&h=750&fit=crop&q=70",
    isNew: true,
    tags: ["haircare", "oil", "repair"],
    sizes: BEAUTY_SIZES,
    description: "Cold-pressed argan oil that repairs split ends, tames frizz, and adds a healthy shine.",
  },
  {
    id: "beauty-4",
    category: "beauty",
    brand: "Pure Earth",
    name: "Shea Butter Body Lotion",
    price: 349,
    originalPrice: 599,
    discountPercent: 42,
    rating: 4.6,
    reviewCount: 1342,
    badge: "50% OFF",
    emoji: "🧼",
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["bodycare", "lotion", "moisturize"],
    sizes: BEAUTY_SIZES,
    description: "A rich shea butter body lotion that absorbs fast and keeps skin soft for up to 48 hours.",
  },
  {
    id: "beauty-5",
    category: "beauty",
    brand: "Sunveil",
    name: "Hyaluronic Sunscreen Gel SPF 50",
    price: 549,
    originalPrice: 899,
    discountPercent: 39,
    rating: 4.5,
    reviewCount: 1789,
    badge: "BESTSELLER",
    emoji: "☀️",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["skincare", "sunscreen", "face"],
    sizes: BEAUTY_SIZES,
    description: "A non-greasy SPF 50 gel with hyaluronic acid — broad-spectrum protection that doubles as a moisturiser.",
  },
  {
    id: "beauty-6",
    category: "beauty",
    brand: "Cocoa & Co.",
    name: "Cocoa Butter Lip Balm Trio",
    price: 249,
    originalPrice: 449,
    discountPercent: 45,
    rating: 4.2,
    reviewCount: 654,
    badge: "UNDER ₹299",
    emoji: "💋",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=750&fit=crop&q=70",
    isNew: false,
    tags: ["lipcare", "balm", "combo"],
    sizes: BEAUTY_SIZES,
    description: "A trio of nourishing cocoa butter lip balms — soothes, softens, and protects chapped lips.",
  },
];

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}
